### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by suchithragl** [JonathanHolvey/sharepy#1]
Hi am trying use this code to connect to my office sharepoint link but it keeps giving username password error. Am pretty sure there is no issue with the credentials. Is it something with authentication mechanism

**Comment by JonathanHolvey** [comment]
Is it an Office 365 SharePoint site? This module is designed specifically for the authentication method used by Office 365 and SharePoint Online.

**Comment by JonathanHolvey** [comment]
@suchithragl Can you provide any further details of the error you're experiencing? Do you receive `Token request failed. Check your username and password` or are there any other messages? Any additional information will be useful to find the root of the problem.

**Comment by JonathanHolvey** [comment]
@suchithragl can you try this again using the latest from `master`?

**Comment by baziliolg** [comment]
Hi,
I had to use `python-2.7` branch, not sure if the issue is the same with `master`.

So this is what I get
```
Enter your username: myuser
Enter your password:
Requesting security token...
Token request failed. Check your username and password
```
No other information is printed on the screen.
I am trying to connect to my company's SharePoint, which I believe is an Office365 service.

**Comment by JonathanHolvey** [comment]
If you're using Office 365 your username should include your domain, for example myuser@mydomain.com.

Although I haven't looked at it in a while, I think the `python-2.7` branch should work fine for the most part.

**Comment by wmetryka-catalogic** [comment]
I am getting the same issue with the newest release. I am connecting to an Office 365 sharepoint and tried both including my domain (user@domain.com) as well as just the username. I can connect just fine using [Office365-REST-Python-Client](https://github.com/vgrem/Office365-REST-Python-Client) using the same exact credentials.
