### ISSUE TITLE
Auth Failure: Direct login to WLID not allowed for federate name space

### ISSUE THREAD

**Issue by egalgano** [JonathanHolvey/sharepy#10]
Hi Jonathan,

I am using your library to try and connect to my organization's sharepoint and download files. However, when I try to access the file I need I get : "Authentication Failure: Direct login to WLID is not allowed for this federated namespace". Have you seen this before / can your library handle this issue? I recognize that there is also a possibility that this is a configuration issue on my organization's side.

Thanks,
Emma

**Comment by JonathanHolvey** [comment]
This isn't an error I've seen before, however I've only just incorporated errors from the authentication server into the status messages in version 1.3.0. Have you been able to connect successfully in the past?

**Comment by egalgano** [comment]
No, this is the first time I have tried to connect. Let me know if you have any trouble shooting ideas.

Thanks,
Emma

**Comment by JonathanHolvey** [comment]
Is it an Office 365 or on-premises SharePoint site?

**Comment by egalgano** [comment]
It's Office 365

**Comment by JonathanHolvey** [comment]
Hmm, this is strange. It looks like your organisation's SharePoint site is configured to use [federated identity](https://docs.microsoft.com/en-us/azure/architecture/patterns/federated-identity) authentication, where authentication is offloaded to another web service, such as an existing Active Directory server. It looks like the SOAP authentication that SharePy uses isn't compatible with this method, or it isn't allowed, as the error message says.

I'm looking for documentation on how this is meant to be handled, but I haven't found anything useful so far...

**Comment by egalgano** [comment]
Sure! Thank you so much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JonathanHolvey** [comment]
I've created a branch `auth-classes` where I've started working on allowing multiple authentication methods. The first step is to detect whether ADFS is in use. Can you check out this branch and run the following?

```
import sharepy
s = sharepy.connect(<your site URL>)
print(s.auth.auth_url)
```

If that runs without errors, and the value of `s.auth.auth_url` looks sensible, I think I should be on the right track. Let me know what you get.

**Comment by egalgano** [comment]
Hi Jonathan,

This is the error message I am getting:

[cid:image002.png@01D4145F.58A4F000]

I am getting this same message if I input my username in password into the sharepy.connect() as well.

Thanks,
Emma

**Comment by JonathanHolvey** [comment]
Thanks for your reply. It looks like you responded to a notification email with a screenshot, but that's not showing up here. Can you edit your comment to include the output you got?

**Comment by egalgano** [comment]
![image](https://user-images.githubusercontent.com/39060558/42383038-1392d2e0-8104-11e8-8fcb-6440c5e0259b.png)

**Comment by JonathanHolvey** [comment]
Ok, I got the XML node name wrong which caused the AttributeError you're seeing.

An easier way is for you to visit the following URL in your browser, inserting your username in place of `username`:

    https://https://login.microsoftonline.com/GetUserRealm.srf?login=username&xml=1

Please confirm that the nodes `<NameSpaceType>` and `<STSAuthURL>` exist in the response XML. The value of `<STSAuthURL>` should be `Federated`.

**Comment by egalgano** [comment]
Hi Jonathan,

I was able to attain the xml once I added my password in the url as well.

The value of <NameSpaceType> is Federated and the value of <STSAuthURL> is https://roivant.okta.com/app/office365/exk1innsc6AxYotiB1t7/sso/wsfed/active

**Comment by JonathanHolvey** [comment]
Thanks for that.

Just to confirm, the URL I gave you didn't work, but one with both username and password did? What was the format you used?

**Comment by egalgano** [comment]
Yeah. I used:

`https://login.microsoftonline.com/GetUserRealm.srf?login=username&password=password&xml=1`

**Comment by JonathanHolvey** [comment]
What did you get when you didn't include the password?

**Comment by egalgano** [comment]
I actually must have mistyped the url because now I am getting the same thing so the original url you provided seems to work.

**Comment by JonathanHolvey** [comment]
I've had a bit of time to start looking at this again.

I've just pushed an update to the `auth-classes` branch, which progresses a little with the ADFS authentication.

Can you check out this branch and attempt to connect using `sharepy.connect()`? It should print out a block of XML which includes a node `<Assertion>`. It may look like `<ns:Assertion>`, where `ns` is an XML namespace. Can you confirm what this is?

**Comment by isaacanderson** [comment]
I didn't experience the same original issue as the reporter but can confirm that the changes in the develop branch to detect and allow federated authentication with ADFS work for me.
