### ISSUE TITLE
Connection fails saying - Invalid Request: The partner DNS used in the login request cannot be found

### ISSUE THREAD

**Issue by prajumau** [JonathanHolvey/sharepy#12]
I am trying to connect to a sharepoint server using the sharepy.connect function. For the same credentials it lets me connect the server through a web browser.

But when i try connecting through my python code it throws the following error :- 
**Invalid Request: The partner DNS used in the login request cannot be found**

Any idea why this is happening

**Comment by JonathanHolvey** [comment]
Is it a SharePoint Online or an on premises site you're trying to connect to?

**Comment by prajumau** [comment]
It is based off of the organizations website site... Say for a company XYZ the site is docs.XYZ.com/..../.../...

**Comment by JonathanHolvey** [comment]
When you log in using your browser, are you taken to `https://login.microsoftonline.com`?
