### ISSUE TITLE
guest authentication

### ISSUE THREAD

**Issue by picousse** [JonathanHolvey/sharepy#16]
Hi,
is there a way to use a guest authentication for sharepoints?
I would like to write a script, running on a server, but I don't feel like putting my password on the server.
Therefor I added a guest account to the sharepoint, which is able to read the sharepoint on the website. However I can't login using the authentication system from sharepy.
Any suggestions for doing this?
Best regards,

**Comment by JonathanHolvey** [comment]
A few questions:
- Is the guest account a special type of user account, or a normal account reserved for guests?
- Does this guest account have the password disabled somehow?
- Do you receive any error messages when trying to connect using SharePy?

**Comment by picousse** [comment]
hi,
- the guest account seems to be a special kind of user account. all other members are members are called member, that one is called guest. It is an account like for external people, let's say. Basically it is a gmail account that is being used to get in to the sharepoint
- no, it has pasword
- "Token request failed. Check your username and password". (after using s = sharepy.connect("inbiose.sharepoint.com")) But this makes sense as the guest account is only added to a specific site.

**Comment by JonathanHolvey** [comment]
Right, ok. That makes it a little tricky. If you use SharePy 1.3.0, what does the error message say?

**Comment by picousse** [comment]
alright finally got it updated.
error I get now is:
> Invalid Request: The partner DNS used in the login request cannot be found

**Comment by picousse** [comment]
Hi,
Is this something you can work with? or should I look for a different solution?
Thx for the help!

**Comment by picousse** [comment]
Hi.
I might have a look, and come up with a solution on my own. I'll let you know.
I would like to use this library of course, as all the code works with my account.

Thanks for the help anyway!
