### ISSUE TITLE
Issues connecting to sharepoint

### ISSUE THREAD

**Issue by mattbpowell** [JonathanHolvey/sharepy#18]
I am a python noob. I had no troubles accessing Sharepoint Rest API for an HTTP version of SharePoint through the standard requests module. But once I move over to the HTTPS version of my SharePoint server no matter what I seem to do, it won't work. So I am attempting to use this lovely module...

I either get this error when using username "mpowell@company.com"
        File "C:\Python36\lib\site-packages\sharepy\session.py", line 97, in _spauth
              print("{}: {}".format(root.find(".//S:Text", ns).text,
          AttributeError: 'NoneType' object has no attribute 'text'

or when using "mpowell" or "winntdom\\mpowell"
       Authentication Failure: AADSTS90019: No tenant-identifying information found in either the request or implied by any provided credentials
       Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]

I know its something I'm not understanding but I hope that you guys can help.

Some things to know, it is a SharePoint on in intranet location at my work, we don't have standard Office365 accounts, our 365 accounts contain our company address so mine is mpowell@company.com. Unfortunately I cannot share my SharePoint site. I am currently using Python 3.6

**Comment by ferdinandosimonetti** [comment]
Hello. Is your client a Linux one? In this case, you should set _verify=disable_ inside **/etc/python/cert-verification.cfg** file. Or, of course, import inside your Linux machines' certificate trust infrastructure the correct certificates...
I've just installed Python for Windows, so I don't know where the Windows corresponding config file resides.

**Comment by JonathanHolvey** [comment]
Is your SharePoint site hosted on Office365? SharePy only works with O365 sites, and I'm pretty sure you shouldn't be able to connect using plain HTTP.

It would be useful to be able to catch this error and provide feedback accordingly. Can you check out [branch `issue-#18`](/JonathanHolvey/sharepy/tree/issue-%2318), and reply with the contents of the `<Fault>` node from the XML that is printed out when using `sharepy.connect()`?

**Comment by mattbpowell** [comment]
I am not sure if its an Office 365 hosted SharePoint. That said I was able to connect using Requests. Although the issue is on my own network side, they have not enabled SSL Certifications but they have an HTTP and HTTPS version of the sites and have no intention of removing the HTTP version. So I can use requests to connect.  Even still, I have

**Comment by JonathanHolvey** [comment]
If you can connect using plain Requests requests without special authentication, and especially if you're using HTTP, then I'm pretty sure you're using a on-premises SharePoint install. SharePy isn't what you want for this as (apart from not working) it doesn't add any functionality over what Requests gets you. It just adds authentication.
