### ISSUE TITLE
Authentication Failure: AADSTS70002

### ISSUE THREAD

**Issue by jgraham0331** [JonathanHolvey/sharepy#19]
Hello,

I'm getting "Authentication Failure: AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password" when I try to connect with s.connect(<url>).  I know the creds are valid since I use them all the time, and I have validate the URL.

**Comment by fredtony** [comment]
I'm getting the same error. I double and triple checked that I am using the correct login. I can login through the browser with the credentials and it works but not through the sharepy library anymore. I have used this for a year without problems, but it suddenly stopped working today! I did not update to library or change my username/password. Was something changed or why might this happen?

**Comment by JonathanHolvey** [comment]
I'm not seeing this issue on my test SharePoint site, which has no custom configuration at all. Do you know how the authentication is set up on your sites?

**Comment by jgraham0331** [comment]
I don't know the details of how authentication is set up on our site but if it's working fine on your test Sharepoint then it's most likely something in the way ours is set up.  In hindsight, it makes sense why the API would be blocked on the corporate Sharepoint.

**Comment by fredtony** [comment]
I'm also unsure about whether our security guys changed any authentication settings nor how it was set up in the first place, but my guess is that something changed. I'm trying to dig in further to understand what might have changed and if I find anything out, I'll follow up.

**Comment by ameer131** [comment]
Greetings, it looks like I am also facing this and looking out for any solutions. For authentication, we have an internal AD who do the job to provide the token. I believe sharepy should support this but somehow it doesnt work properly.

**Comment by fredtony** [comment]
Our admin said that there were no changes that he made, so I'd guess it has more to do with Microsoft. Although this doesn't seem quite relevant to this problem, I did come across this update from Microsoft: https://developer.microsoft.com/en-us/graph/blogs/upcoming-changes-to-exchange-web-services-ews-api-for-office-365/
The timing of this article seems to align with the library breaking for people on this thread even though the blog post mentions that it won't take effect until 2020. However, this may break the whole library at that point, so it might be important for future development.

**Comment by alenart1** [comment]
Same issue here.  Sharepy worked without any problems for months for me, and now in the last 2 weeks I'm getting:
Authentication Failure: AADSTS70002: Error validating credentials. AADSTS50126: Invalid username or password
And if I try too many times, I get:
Authentication Failure: AADSTS70002: Error validating credentials. AADSTS50053: You've tried to sign in too many times with an incorrect user ID or password

But I am 100% sure I'm using the correct username and password.

**Comment by tschroedertlc** [comment]
Still does not work for me. I have not been able to make any workaround work (with this nor with any other library) with Sharepoint anymore despite some significant time researching the problem, so I do everything manually now.

**Comment by fredtony** [comment]
Still does not work for me. I have not been able to make any workaround work (with this nor with any other library) with Sharepoint anymore despite some significant time researching the problem, so I do everything manually now.

**Comment by JonathanHolvey** [comment]
@fredtony, @ameer131, @alenart1, @jgraham0331 are you able to try the develop branch to see if this issue remains?

**Comment by ameer131** [comment]
@JonathanHolvey I am sorry, I am no longer have access to that environment due to work movement. Perhaps others can help to test.

**Comment by jgraham0331** [comment]
Same situation. I have changed jobs since my original post and no longer have access to test things.
