### ISSUE TITLE
Importing

### ISSUE THREAD

**Issue by Sanjuadit** [JonathanHolvey/sharepy#3]
How to import sharepy ? How to install it in python .

**Comment by JonathanHolvey** [comment]
You should be able to download or clone SharePy into your project folder, then include it using `import sharepy`.

I'm working on submitting SharePy to PyPI, so it can be installed using `python -m pip install sharepy`. I'll let you know when this is ready - hopefully later today.

**Comment by JonathanHolvey** [comment]
SharePy is now available on PyPI, and can be installed using `pip install sharepy`. Let me know if you have issues getting that to work.

**Comment by Sanjuadit** [comment]
Hi Jonathan,

Thanks i'm able to download . I'm not clear about the way it works .
Actually i'm trying to access files from microsoft onedrive provided by my
company .I can see the domain name as "onevmw-my.sharepoint.com"  .

By your module , i gave this domain name . It asked for username and after
i entered my username it simple waits with no results . Can you please help
me helping me to connect to onedrive provided by my company .

Thanks,
Sanjayan

**Comment by JonathanHolvey** [comment]
Are you able to successfully connect to the site? Can you post the code you're using?

**Comment by Sanjuadit** [comment]
I'm just trying to test the connection , i'm not able to connect.

import sharepy
s = sharepy.connect("onevmw-my.sharepoint.com")


It is asking for username , once i give the username . Its waiting and
gives no response.

**Comment by JonathanHolvey** [comment]
Ok, I did find a problem with the PyPI version of SharePy, which would result in an error after entering your username, if you installed using `pip`.

I've released a fixed version, which can be installed using `pip install sharepy --upgrade`.
