### ISSUE TITLE
Uploading a file to a sharepoint folder 

### ISSUE THREAD

**Issue by hishamsajid** [JonathanHolvey/sharepy#31]
I don't think this feature currently exists in this package. Can anyone confirm?

**Comment by JonathanHolvey** [comment]
SharePy doesn't aim to support any particular features of the SharePoint API. It is up to you to build the required requests to carry out the task you're trying to achieve.

In your case, a POST request to the `GetFolderByServerRelativeUrl` endpoint should allow you to create a file in a document library. See the following Stack Exchange question for more details.

https://sharepoint.stackexchange.com/questions/253430/upload-file-to-sharepoint-online-with-http-rest-calls

**Comment by hishamsajid** [comment]
Thanks man, I'll look into this. Keep up the good work!
