### ISSUE TITLE
Saving "Downloaded files" in current work session

### ISSUE THREAD

**Issue by SG-Gank** [JonathanHolvey/sharepy#34]
Hi, I have successfully used the following code to download a dataset. 

"r = s.getfile("https://example.sharepoint.com/Library/Test%20File.pdf", filename="downloads/file.pdf")"

Now I'd like to work with the dataset directly in the same work session without importing the dataset from local drive. For example, as a Pandas dataframe. Any advice on this?

**Comment by ooverandout** [comment]
+1, I would also love to have this sort of function.

Something like copying file to the file-like object:

```
flo = io.BytesIO()
r = s.getfile("https://example.sharepoint.com/Library/Test%20File.pdf", file-object= flo)
```

**Comment by JonathanHolvey** [comment]
You should be able to achieve this by feeding the response from a simple GET request into Python's IO module:
```python
import io
f = io.BytesIO(s.get("https://example.sharepoint.com/Library/Test%20File.pdf").content)
```
