### ISSUE TITLE
Multifactor authentication for sharepoint account

### ISSUE THREAD

**Issue by csdalvi** [JonathanHolvey/sharepy#38]
I am trying to access our company's sharepoint account but there is a multi-factor authentication required to login. Basically we receive a text message containing a one-time password every time we try to login into sharepoint. Due to this, I can connect to sharepoint using python. What are the possible solutions for this?

**Comment by JonathanHolvey** [comment]
Is the MFA a feature that is built into SharePoint, or is it a customisation?

Many services that use MFA get around this issue by allowing you to create 'application passwords', that don't require a prompt but can be easily cycled on demand. This would be the best solution, however, I'm not sure if this is something that's available to you. 

If the MFA is a standard offering that comes with SharePoint, a custom authenticator could be written to work with it. This isn't something I have the time or resources for, however.

**Comment by csdalvi** [comment]
I believe that it is a feature built into Sharepoint.

**Comment by JonathanHolvey** [comment]
This might be useful in that case https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183
