### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by jon85** [JonathanHolvey/sharepy#39]
Hi,

First off, thank you for sharing project!

The development branch fixes some issues we are having after we migrated to ADFS. Is there a release date planned?

Cheers,
Jon

**Comment by JonathanHolvey** [comment]
Hi @jon85,

I've got a version 2 release of SharePy drafted, which includes the ADFS support you mentioned.

I've done a bit of refactoring in preparation for the release, but I don't have an ADFS site to test it with. Would you be able to try out the release branch and let me know if there are any issues?

https://github.com/JonathanHolvey/sharepy/tree/release-2.0.0-beta

Thanks for your help.
