### ISSUE TITLE
Authentication failure AADSTS50126: Error validating credentials due to invalid username or password

### ISSUE THREAD

**Issue by rajmetti** [JonathanHolvey/sharepy#41]
i gave correct credentials and url but dont know its giving this error below is the code that im using
import sharepy
from sharepy import connect 
from sharepy import SharePointSession

server="https://company.sharepoint.com"
user="user@company.com" // username
password="passcode" //passcode

s = sharepy.connect(server,user,password)

**Comment by JonathanHolvey** [comment]
Please see #42
