### ISSUE TITLE
Accessing data on subsite

### ISSUE THREAD

**Issue by JonathanHolvey** [JonathanHolvey/sharepy#44]
@alex00321 said:

> Hi I'm new to this case, but I'm trying to use sharePy to post file. The problem I got here is I don't have the main site like company.sharepoint.com. I only could access the sub site like company.sharepoint.com/sites/mine. So is there any way you could help? Thanks!

Copied from https://github.com/JonathanHolvey/sharepy/issues/42#issuecomment-643986524

**Comment by JonathanHolvey** [comment]
You can access pages on a subsite by passing the full URL when making a request. Something like:

```python
import sharepy
s = sharepy.connect("company.sharepoint.com")

r = s.get("https://company.sharepoint.com/sites/mine/")
```

**Comment by alex00321** [comment]
Thanks for the feedback @JonathanHolvey  but this is still returning with"Authentication Failure: AADSTS50126: Error validating credentials due to invalid username or password"

**Comment by JonathanHolvey** [comment]
Ok, I'll close this issue in that case. I'll see if I can have a look at #42 now that the XML data I need has been provided.
