### ISSUE TITLE
Download Files Sharepoint Online

### ISSUE THREAD

**Issue by tremy92** [JonathanHolvey/sharepy#5]
Hi,
Thank you for this python applet, complete and light.

I've been looking for a long time how to upload a set of files to a sharepoint online document library in a recursive way..

mysite.sharepoint.com/subsites/namesite/Documents/ ..

I don't know how to write the download function of a complete directory.

Can you help me ?

I thank you in advance for you help,

**Comment by JonathanHolvey** [comment]
Do you want to upload or download the files?

**Comment by tremy92** [comment]
Hi Jonathan,

Sorry I'm French, it's bad traduction

I want "Download" many files in repertory. Yesterday I try your function "Get-files" but I want download many files on a repertory.

I search also with "Office365-RestPython" but it's very complex for me..

Thank you very much, thank you again for your help.

Good day,

M. REMY Thibault.

**Comment by JonathanHolvey** [comment]
[This StackExchange answer](https://sharepoint.stackexchange.com/a/159135/53657) describes how to get a list of all files and folders in a library. Using this, I came up with the following script to download all the files:

```python
import os
import sharepy

s = sharepy.connect("https://example.sharepoint.com")
site = "https://example.sharepoint.com/sites/test"
library = "Test Library"

# Get list of all files and folders in library
files = s.get("{}/_api/web/lists/GetByTitle('{}')/items?$select=FileLeafRef,FileRef"
              .format(site, library)).json()["d"]["results"]

for file in files:
    source = "https://" + s.site + file["FileRef"]
    dest = "." + file["FileRef"]
    # Check if item is file or folder
    folder = s.get("{}/_api/web/GetFolderByServerRelativeUrl('{}')"
                   .format(site, file["FileRef"])).status_code == 200
    print(source)

    if not os.path.exists(dest):
        if folder:
            os.makedirs(dest)  # Create folders
        else:
            s.getfile(source, filename=dest)  # Download files
```

**Comment by tremy92** [comment]
Jonathan,
This is perfect and corresponds to my will.
I think it will help other people.
Thank you very much,
M. REMY Thibault.

**Comment by tremy92** [comment]
Jonathan,
You can close this Issues.
Just for me, for get all recursively repertory, I use : 

	files = s.get("{}/_api/web/lists/getbyTitle('{}')/Items?$select=FileLeafRef,FileRef,Id&$top=5000"
			  .format(site, library)).json()["d"]["results"]

Thank you for your help,
M. REMY Thibault.

**Comment by tremy92** [comment]
Hi,

Below is a correction to the Download code.

The initial REST request sends an error for the directory download containing special characters (example: ' )

Here is the corrected code:

`folder = s.get("{}/_api/web/GetFolderByServerRelativeUrl('{}')"
		.format(site, file["FileRef"].replace("'","''"))).status_code == 200
`
Best Regards,
M. REMY Thibault.

**Comment by iamericha** [comment]
Hi Jonathan,

Forgive this question if it has already been answered, I just recently came across your sharepy module.  This bit of code is great.  Is there a way to download files in a Folder that's within a Library?  For instance, with your code above, if there was a folder called "ABC" in the "Test Library" library you have in your example, how would I download all the files within that folder?

**Comment by JonathanHolvey** [comment]
@iamericha you're in the right place. I believe the script I posted [above](#issuecomment-354729381) should do most of what you're after. If you only want files from a specific folder, you can check each file path before downloading:

```python
# Get all files and folders recursively (thanks tremy92)
files = s.get("{}/_api/web/lists/getbyTitle('{}')/Items?$select=FileLeafRef,FileRef,Id&$top=5000"
		  .format(site, library)).json()["d"]["results"]
for file in files:
    if file["FileRef"].startswith("/Test Library/The Folder"):
        # Download files here
```
You might need to check the format of the paths stored in the `FileRef` property, but otherwise I think it should work.

**Comment by iamericha** [comment]
Thank you Jonathan, I'll give it a try and see how it goes.

**Comment by iamericha** [comment]
This worked beautifully, thank you Jonathan.

**Comment by JfitzGit** [comment]
Many thanks Jonathan!

**Comment by ahowl7mx** [comment]
I tried it but received a KeyError: 'd'

 .format(site, library)).json()["d"]["results"]

What does it mean?  I may not have json loaded.

**Comment by sbi-rviot** [comment]
Hello,
Those answers where very helpful. 
I might need to open a new question for this, so please let me know if it is the case.

I cannot find, using this library **Sharepy**, which I find so far very useful, a way to read a file (meaning its content) instead of downloading it. 

Is there an equivalent to "getfile" that would be something like "readfile". I have seen the following functions that are built in **Sharepy** session but it doesn't seem to do the trick ( ___init__, _spauth, _redigest, save, post, getfile, _buildcookie_).

I can give piece of code if the description of my problem is not clear enough. 

Thank you

**Comment by ashokmagadum** [comment]
> [This StackExchange answer](https://sharepoint.stackexchange.com/a/159135/53657) describes how to get a list of all files and folders in a library. Using this, I came up with the following script to download all the files:
> 
> ```python
> import os
> import sharepy
> 
> s = sharepy.connect("https://example.sharepoint.com")
> site = "https://example.sharepoint.com/sites/test"
> library = "Test Library"
> 
> # Get list of all files and folders in library
> files = s.get("{}/_api/web/lists/GetByTitle('{}')/items?$select=FileLeafRef,FileRef"
>               .format(site, library)).json()["d"]["results"]
> 
> for file in files:
>     source = "https://" + s.site + file["FileRef"]
>     dest = "." + file["FileRef"]
>     # Check if item is file or folder
>     folder = s.get("{}/_api/web/GetFolderByServerRelativeUrl('{}')"
>                    .format(site, file["FileRef"])).status_code == 200
>     print(source)
> 
>     if not os.path.exists(dest):
>         if folder:
>             os.makedirs(dest)  # Create folders
>         else:
>             s.getfile(source, filename=dest)  # Download files
> ```

Hi Jonathan,

I observed weird behaviour while listing folders in this code.
```
# Get list of all files and folders in library
files = s.get("{}/_api/web/lists/GetByTitle('{}')/items?$select=FileLeafRef,FileRef"
               .format(site, library)).json()["d"]["results"]
```

If Sharepoint library has 50 folders, all 50 folders are listed in "files" variable.
But, if library has 55 folders, then only 45 folders are listed in "files" variable.
If library has 53 folders, then 47 folders are listed in "files" variable.
If library has 51 folders, then 49 folders are listed in "files" variable.

If library has 56 or more folders, then only 39 folders are listed in "files" variable.


Wondering, if you could help me with this.

**Comment by vikramnr** [comment]
@JonathanHolvey , I was able to follow this issue and was able to get the list of files are folders, but I have nested folder inside so the example code is creating the folder structure but not actually downloading the files inside that nested folder?

I tried get by title, but since the folder that I have doesn't have a title, I'm not able to use `GetByTitle`. Could you please advise how to proceed from here?


```
    if not os.path.exists(dest):
        if folder:
            os.makedirs(dest)  # Create folders

```

**Comment by DarkKavon** [comment]
> [This StackExchange answer](https://sharepoint.stackexchange.com/a/159135/53657) describes how to get a list of all files and folders in a library. Using this, I came up with the following script to download all the files:
> 
> ```python
> import os
> import sharepy
> 
> s = sharepy.connect("https://example.sharepoint.com")
> site = "https://example.sharepoint.com/sites/test"
> library = "Test Library"
> 
> # Get list of all files and folders in library
> files = s.get("{}/_api/web/lists/GetByTitle('{}')/items?$select=FileLeafRef,FileRef"
>               .format(site, library)).json()["d"]["results"]
> 
> for file in files:
>     source = "https://" + s.site + file["FileRef"]
>     dest = "." + file["FileRef"]
>     # Check if item is file or folder
>     folder = s.get("{}/_api/web/GetFolderByServerRelativeUrl('{}')"
>                    .format(site, file["FileRef"])).status_code == 200
>     print(source)
> 
>     if not os.path.exists(dest):
>         if folder:
>             os.makedirs(dest)  # Create folders
>         else:
>             s.getfile(source, filename=dest)  # Download files
> ```

I think that there should be 
```
if not os.path.exists(dest):
         if not folder:
             os.makedirs(dest)  # Create folders
         else:
             s.getfile(source, filename=dest)  # Download files
```
it did not work for me without this 'not' because there was no destination folder

**Comment by ahyimi** [comment]
> @iamericha you're in the right place. I believe the script I posted [above](#issuecomment-354729381) should do most of what you're after. If you only want files from a specific folder, you can check each file path before downloading:
> 
> ```python
> # Get all files and folders recursively (thanks tremy92)
> files = s.get("{}/_api/web/lists/getbyTitle('{}')/Items?$select=FileLeafRef,FileRef,Id&$top=5000"
> 		  .format(site, library)).json()["d"]["results"]
> for file in files:
>     if file["FileRef"].startswith("/Test Library/The Folder"):
>         # Download files here
> ```
> 
> You might need to check the format of the paths stored in the `FileRef` property, but otherwise I think it should work.

hello @JonathanHolvey, if I am trying to download all the files within 4 (or more) subfolders which is inside the main folder named 'Reports' in Sharepoint. I am not planning to use sharepy actually. But in case you have an idea to solve this, i would truly appreciate it.

I used the following code:

```
url = 'https://HAHA.sharepoint.com/sites/Forms/Reports/'
import getpass
domain = 'HAHA.sharepoint.com' 
user = getpass.getuser() 
pwd = getpass.getpass(prompt='What is your windows AD password?')
 

import requests
from requests_ntlm import HttpNtlmAuth
from urllib.parse import unquote
from pathlib import Path

 
filename = unquote(Path(url).name)
response = requests.get(url, auth=HttpNtlmAuth(f'{domain}\\{user}', pwd ))


for file in filename:
        with open(filename, 'wb') as local_file:
            local_file.write(response.content))
```
However, I get an error `[OSError: [Errno 22] Invalid argument: 'AllItems.aspx?FolderCTID=0x0120001B8F714072E1184781C4A5E4969E4CC9&id=/Reports'](url)
`
 I'm wondering if this code is specifically downloading one file. I want to download the whole folder and its sub-folders and the files within the subfolders.
