### ISSUE TITLE
Getting a 403 message when trying to create a new list item

### ISSUE THREAD

**Issue by GarrickVCertarus** [JonathanHolvey/sharepy#63]
I have an integration using Sharepy that suddenly stopped working about 2 weeks ago (the last commit was 9 months ago).

Post requests to create new SharePoint list items do not appear to be working anymore, the request below:

`sharepy.post("https://xxxxxxxxx.sharepoint.com/sites/xxxSite/_api/web/lists/getByTitle('Test List')/items", data)`

gives the following forbidden error:

'{"error":{"code":"-2130575251, System.Runtime.InteropServices.COMException","message":{"lang":"en-US","value":"The security validation for this page is invalid. Click Back in your Web browser, refresh the page, and try your operation again."}}}'

I assumed that this might have something to do with the request digest since Get requests are not broken, but it appears the Sharepy object does contain the digest.

**Comment by JonathanHolvey** [comment]
There is an issue in SharePy v2 that prevents POST requests from being authenticated properly. Until this is fixed, I recommend using the previous release, which is v1.3.0. See #49 and #59

**Comment by GarrickVCertarus** [comment]
Thanks for the response, I have ensured that it uses v1.3.0, and everything is back up and running.

**Comment by puntomaupunto** [comment]
> There is an issue in SharePy v2 that prevents POST requests from being authenticated properly. Until this is fixed, I recommend using the previous release, which is v1.3.0. 

Is the issue fixed? I am trying to upload files to my shrepoint, but I get error 403 too. 
(moreover, I downloaded 1.3.0, but I noticed that the authentication is different, so I cannot login to my own sharepoint site...)
