### ISSUE TITLE
Problems importing sharepy

### ISSUE THREAD

**Issue by Elliebee79** [JonathanHolvey/sharepy#7]
I am getting a syntax error when I try to import sharepy:  line 78
    print("Requesting security token...\r", end="")

**Comment by JonathanHolvey** [comment]
Are you using Python 2? The syntax for printing changed between Python 2 and 3, and SharePy's master branch currently only works with Python 3. You can try the python-2.7 branch instead, however it may be a little out of date compared with master.

**Comment by Elliebee79** [comment]
I am using Python 2.7  Where can I find the 2.7 branch?
