### ISSUE TITLE
Question: on-premises auth?

### ISSUE THREAD

**Issue by wjehenddher** [JonathanHolvey/sharepy#8]
Hello:

Noticed that the authentication relies on microsoft online.

Any suggestion about on-premises authentication?

https://github.com/JonathanHolvey/sharepy/blob/ffe4f6846b984c2ba40e58271e8d97bea2375d21/session.py#L79

We're evaluating sharepy as an alternative to https://github.com/requests/requests-ntlm

**Comment by JonathanHolvey** [comment]
SharePy is intended only to solve the problem of authenticating with Office365.

For on-premises installations, you will have to work with the authentication method used by your site. I've had success in the past using `requests-ntlm` for an on-premises site which authenticates using Windows domain credentials.

**Comment by wjehenddher** [comment]
Thank you @JonathanHolvey 

We were also able to authenticate and upload files using `requests-ntlm` for our on-premises env.

I'll close this issue.
